name: Test deployment

on:
  schedule:
     - cron: '55 22 * * *' # AM 07:55, South Korea!
  workflow_dispatch:
      inputs:
         logLevel:
            description: 'Log level'     
            required: true
            default: 'warning'
         tags:
            description: 'Test scenario tags'
jobs:
  test-deploy:
    name: Test deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
      - name: Git Sumbodule Update
        run:
         git pull --recurse-submodules
         git submodule update --remote --recursive
      - name: Test build website
        run: npm run build
